# Generated by Django 5.0.6 on 2024-07-02 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
        migrations.AddField(
            model_name='about',
            name='short_description',
            field=models.TextField(default=datetime.datetime(2024, 7, 2, 14, 39, 8, 76735, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='about/'),
        ),
    ]
